-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 10:43:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bunnyapi
-- -----------------------------------------------------
-- Database model for CSIS3381 IAS Bash Bunny project
DROP SCHEMA IF EXISTS `bunnyapi` ;

-- -----------------------------------------------------
-- Schema bunnyapi
--
-- Database model for CSIS3381 IAS Bash Bunny project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bunnyapi` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bunnyapi` ;

-- -----------------------------------------------------
-- Table `bunnyapi`.`chrome_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bunnyapi`.`chrome_data` ;

CREATE TABLE IF NOT EXISTS `bunnyapi`.`chrome_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataset` INT NOT NULL,
  `chrome_url` LONGTEXT NULL,
  `chrome_user` LONGTEXT NULL,
  `chrome_pw` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS bunny_readonly;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'bunny_readonly' IDENTIFIED BY 'sPlG3caeDS?7';

GRANT SELECT ON TABLE `bunnyapi`.* TO 'bunny_readonly';
SET SQL_MODE = '';
DROP USER IF EXISTS bunny_write;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'bunny_write' IDENTIFIED BY 'sVMPx32ZuG?7';

GRANT SELECT, INSERT, TRIGGER ON TABLE `bunnyapi`.* TO 'bunny_write';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
