SET SQL_MODE = '';
DROP USER IF EXISTS bunny_readonly;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'bunny_readonly' IDENTIFIED WITH mysql_native_password BY 'sPlG3caeDS?7';
GRANT SELECT ON TABLE `bunnyapi`.* TO 'bunny_readonly';

SET SQL_MODE = '';
DROP USER IF EXISTS bunny_write;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'bunny_write' IDENTIFIED WITH mysql_native_password BY 'sVMPx32ZuG?7';
GRANT SELECT, INSERT, TRIGGER ON TABLE `bunnyapi`.* TO 'bunny_write';
